### ISSUE TITLE
Find all variables used in a procedure, and if they are input or output - doesn't work

### ISSUE THREAD

**Issue by opensource21** [JannikArndt/Canal#19]
Can you explain how to enable the feature "Find all variables used in a procedure, and if they are input or output". Can't find it in 2.8.0
Would be a great feature

**Comment by JannikArndt** [comment]
You can double click a procedure name in the code or select it in the table of contents.

**Comment by opensource21** [comment]
Now it works, no idea at which procedure it yesterday failed. Anyway great feature! Does it list only variables which are directly changed in the procedure or does it works recursive?

**Comment by JannikArndt** [comment]
It is not recursive, but that is a great idea for a feature request!
Also note that it's not 100% accurate!
